name: Some workflow

on:
  push:
  workflow_dispatch:
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository to the runner
      uses: actions/checkout@v4
    - name: Run a script
      run: |
        echo "Hello"
        exit 0
   
